<img src="./unal.png" align=left width="150" height="150"></img>

$\;$
---

<h2 align="center">CONCATENANDO Y UNIENDO (Series y DataFrame)</h2>

In [5]:
import pandas as pd
import numpy as np
#pd.options.display.float_format = '{:.2f}'.format
np.set_printoptions(precision=1)

In [7]:
x=np.random.randn()     #genera un número aleatorio entre 0-1
x

0.03559074695301078

In [9]:
x1=np.random.rand(2,5)*10       #genera una matrix de 2*5 con valores entre 0 - 10
x1

array([[6.6, 9.1, 4.9, 5.5, 3.4],
       [1.7, 0.7, 7.2, 6.3, 8.7]])

In [10]:
x2 = np.random.rand(2,5)*-1    #genera matriz de 2*5 con valores negativos
x2

array([[-0.9, -0.4, -0. , -0.7, -0.3],
       [-0.4, -0.7, -0.7, -0.1, -0.3]])

In [18]:
df = np.concatenate([x1,x2])
print(df)
print(f'Esta es una matriz de dimensiones {df.shape}, es decir que concatenate concatena por filas.')

[[ 6.6  9.1  4.9  5.5  3.4]
 [ 1.7  0.7  7.2  6.3  8.7]
 [-0.9 -0.4 -0.  -0.7 -0.3]
 [-0.4 -0.7 -0.7 -0.1 -0.3]]
Esta es una matriz de dimensiones (4, 5), es decir que concatenate concatena por filas.


In [25]:
df2=np.concatenate([x1,x2],axis=1)
print(df2)
print('Esta es una matriz de dimensiones {}, es decir que concatenate concatena por columnas.'.format(df2.shape))

[[ 6.6  9.1  4.9  5.5  3.4 -0.9 -0.4 -0.  -0.7 -0.3]
 [ 1.7  0.7  7.2  6.3  8.7 -0.4 -0.7 -0.7 -0.1 -0.3]]
Esta es una matriz de dimensiones (2, 10), es decir que concatenate concatena por columnas.


--- 
### Series
---

In [25]:
s1 = pd.Series(x1[0],index = ['a','b','c','d','e'])
s1

a   5.76
b   9.79
c   5.37
d   5.70
e   5.99
dtype: float64

In [26]:
s2 = pd.Series(x2[0],index = ['c','d','e','f','g'])
s2

c   -0.72
d   -0.70
e   -0.53
f   -0.42
g   -0.31
dtype: float64

In [27]:
pd.concat([s1,s2])

a    5.76
b    9.79
c    5.37
d    5.70
e    5.99
c   -0.72
d   -0.70
e   -0.53
f   -0.42
g   -0.31
dtype: float64

In [28]:
pd.concat([s1,s2], axis=1)

0     1
a 5.76   nan
b 9.79   nan
c 5.37 -0.72
d 5.70 -0.70
e 5.99 -0.53
f  nan -0.42
g  nan -0.31

In [29]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 8.08 2.08
1 2.18 4.32
2 3.79 7.19

In [30]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'], index = [2,3,4])
df2

a     b
2 -0.45 -0.79
3 -0.84 -0.99
4 -0.83 -0.65

In [31]:
pd.concat([df1,df2])

a     b
0  8.08  2.08
1  2.18  4.32
2  3.79  7.19
2 -0.45 -0.79
3 -0.84 -0.99
4 -0.83 -0.65

In [32]:
pd.concat([df1,df2],axis=1)

a    b     a     b
0 8.08 2.08   nan   nan
1 2.18 4.32   nan   nan
2 3.79 7.19 -0.45 -0.79
3  nan  nan -0.84 -0.99
4  nan  nan -0.83 -0.65

In [33]:
pd.concat([df1,df2], axis=1, join='inner')

a    b     a     b
2 3.79 7.19 -0.45 -0.79

In [34]:
pd.concat([
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis=1)

a    b     a     b
0 8.08 2.08 -0.45 -0.79
1 2.18 4.32 -0.84 -0.99
2 3.79 7.19 -0.83 -0.65

In [38]:
df1.append(df2).append(df2)

a     b
0  8.08  2.08
1  2.18  4.32
2  3.79  7.19
2 -0.45 -0.79
3 -0.84 -0.99
4 -0.83 -0.65
2 -0.45 -0.79
3 -0.84 -0.99
4 -0.83 -0.65

In [36]:
df1.T

0    1    2
a 8.08 2.18 3.79
b 2.08 4.32 7.19

In [39]:
df1.T.append(df2.T).T

a    b     a     b
0 8.08 2.08   nan   nan
1 2.18 4.32   nan   nan
2 3.79 7.19 -0.45 -0.79
3  nan  nan -0.84 -0.99
4  nan  nan -0.83 -0.65